* import version 2.2.3 from ubuntu11.10

diff --git a/utils/sb2-init b/utils/sb2-init
--- a/utils/sb2-init
+++ b/utils/sb2-init
@@ -70,8 +70,6 @@ are available by version number (e.g. if the primary is known as
 Options:
     -c "command"      specify cpu transparency command, for example:
                       "qemu-arm", "sbrsh" or "qemu-arm -m 512"
-    -p "command"      specify cpu transparency command for staticly linked
-                      native binaries
     -r [hostname]     generate sbrsh config using remote device address
     -l [hostname]     NFS server/localhost address seen by remote device
     -d                set target as default scratchbox2 target
@@ -83,8 +81,6 @@ Options:
     -t [tools_dir]    set directory containing the build tools distribution
     -C "options"      add extra options for the compiler, for example:
                       "-fgnu89-inline"
-    -L "options"      add extra options for the linker, for example:
-                      "--sysroot=/"
     -A arch           manually override target architecture
     -M arch           manually override machine name (see uname(2)). This
                       defaults to the target architecture (see option -A)
@@ -107,7 +103,7 @@ function version()
 }
 
 # Create the old-style configuration file.
-# TODO: This system will be replaced by smaller configuration files
+# TODO: This system will be replaced by smaller configuration files 
 # that live in $SBOX_CONFIG_DIR directory.
 function write_target_config()
 {
@@ -124,11 +120,10 @@ SBOX_TARGET_ROOT=$SBOX_TARGET_ROOT
 
 SBOX_CPU=$ARCH
 SBOX_CPUTRANSPARENCY_METHOD="$SB2INIT_CPUTRANSP"
-SBOX_CPUTRANSPARENCY_NATIVE_METHOD="$SB2INIT_CPUTRANSP_NATIVE"
 SBOX_UNAME_MACHINE=$MACHINE_ARCH
 
-SBOX_HOST_GCC_NAME="$SB2INIT_SBOX_HOST_GCC_NAME"
-SBOX_HOST_GCC_PREFIX_LIST="$SB2INIT_SBOX_HOST_GCC_PREFIX_LIST"
+SBOX_HOST_GCC_NAME=host-gcc
+SBOX_HOST_GCC_PREFIX_LIST=host-
 SBOX_HOST_GCC_SUBST_PREFIX=
 SBOX_HOST_GCC_SPECS_FILE=
 SBOX_HOST_GCC_DIR=/usr/bin
@@ -174,33 +169,22 @@ function check_buildroot_sanity()
 	fi
 
 	if [ ! -e lib/libc.so.6 ] && [ ! -e lib/libc.so.0 ]; then
-		echo "no lib/libc.so.6 or lib/libc.so.0; searching for multiarch..."
-		if [ ! -e lib/$SB2INIT_MULTIARCH_PATH/libc.so.6 ] && [ ! -e lib/$SB2INIT_MULTIARCH_PATH/libc.so.6 ];then
-			echo "also no lib/$SB2INIT_MULTIARCH_PATH/libc.so.6 or lib/$SB2INIT_MULTIARCH_PATH/libc.so.0"
-			a_ok=0
-		else
-			echo "don't worry, there are lib/$SB2INIT_MULTIARCH_PATH/libc.so.6 and lib/$SB2INIT_MULTIARCH_PATH/libc.so.0"
-		fi
+		echo "no lib/libc.so.6 or lib/libc.so.0"
+		a_ok=0
 	fi
 
 	if [ ! -e usr/lib/libc.so ]; then
-		echo "no usr/lib/libc.so; searching for multiarch..."
-		if [ ! -e usr/lib/$SB2INIT_MULTIARCH_PATH/libc.so ];then
-			echo "no usr/lib/$SB2INIT_MULTIARCH_PATH/libc.so"
-			a_ok=0
-		else
-			echo "don't worry, there is usr/lib/$SB2INIT_MULTIARCH_PATH/libc.so"
-		fi
+		echo "no usr/lib/libc.so"
+		a_ok=0
 	fi
-
+	
 	if [ $a_ok == 1 ]; then
 		true
 	else
-		echo "Your buildroot seems to lack basic essentials like headers
+		echo "Your buildroot seems to lack basic essentials like headers 
 or c-library. You should probably get either a ready rootfs tarball or
 copy the necessary files from your toolchain into place. After doing that
 you can re-run this script."
-		echo "Or you just chroot in and apt-get install libc6-dev dpkg-dev"
 		exit 1
 	fi
 }
@@ -231,7 +215,6 @@ function configure_toolchains()
 			-t "$TARGET" \
 			-m "$MAPPING_MODE" \
 			-C "$SB2INIT_SBOX_EXTRA_CROSS_COMPILER_ARGS" \
-			-L "$SB2INIT_SBOX_EXTRA_CROSS_LD_ARGS" \
 			-- \
 			$compiler_path
 		if [ $? != 0 ]; then
@@ -273,7 +256,7 @@ if [ -z "$SBOX_INIT_ORIG_ARGS" ]; then
 fi
 
 # Parse parameters (round 1); don't write anything to the config directory yet,
-# because a) name of the target is currently unknown, b) there might be
+# because a) name of the target is currently unknown, b) there might be 
 # errors in the parameters, or c) if the user is just requesting help or
 # version and we are not actually going to configure anything.
 eval `$SBOX_SHARE_DIR/scripts/sb2-parse-sb2-init-args "${init_orig_args_array[@]}"`
@@ -297,23 +280,17 @@ if [ "$SB2INIT_LOCALHOST" ] && [ -z "$SB2INIT_REMOTEHOST" ]; then
 	echo "Warning: Local host specified without remote host."
 fi
 
-case "$TARGET" in
-	*/*)
-		echo "Error: Illegal character (/) in target name"
-		exit 1
-		;;
-	"")
-		echo "Error: no target given"
-		exit 1
-		;;
-esac
+if [ -z "$TARGET" ]; then
+	echo "Error: no target given"
+	exit 1
+fi
 
 if [ -z "$MAPPING_MODE" ]; then
 	MAPPING_MODE="simple"
 	echo "Info: Mapping mode not specified, using default ($MAPPING_MODE)"
 fi
 
-if [ ! -d $SBOX_DIR/share/scratchbox2/modes/$MAPPING_MODE ]; then
+if [ ! -d $SBOX_DIR/share/scratchbox2/lua_scripts/pathmaps/$MAPPING_MODE ]; then
 	echo "Invalid mapping mode: $MAPPING_MODE"
 	exit 1
 fi
@@ -322,9 +299,9 @@ fi
 
 mkdir -p $HOME/.scratchbox2/$TARGET
 
-SBOX_CONFIG_DIR=~/.scratchbox2/$TARGET/sb2.config.d
+SBOX_CONFIG_DIR=~/.scratchbox2/$TARGET/sb2.config.d 
 if [ ! -d $SBOX_CONFIG_DIR ]; then
-        mkdir $SBOX_CONFIG_DIR
+        mkdir $SBOX_CONFIG_DIR 
 fi
 log_config_action "sb2-init $SBOX_INIT_ORIG_ARGS"
 
@@ -393,7 +370,7 @@ if ! expr "$ARCH" : "$HOST_ARCH" > /dev/null ; then
 		if [ -z "$DEFAULT_CPUTRANSP" ]; then
 			# ...and there is no default CPU transparency method.
 			# This may be an error, or may not be: If one has a 64-bit host,
-			# but develops for an 32-bit Intel target, the architecture
+			# but develops for an 32-bit Intel target, the architecture 
 			# strings are different but Qemu is not needed.
 			echo "sb2-init: WARNING:"
 			echo "sb2-init: *******  Host architecture is different than target architecture,"
@@ -414,50 +391,15 @@ if ! expr "$ARCH" : "$HOST_ARCH" > /dev/null ; then
 			fi
 		fi
 	fi
-	if [ -n "$SB2INIT_CPUTRANSP" ]; then
-		if [ -e "$SB2INIT_CPUTRANSP" ]; then
-			case `file $SB2INIT_CPUTRANSP` in
-				*dynamically*)
-					# This is OK.
-					;;
-				*statically*)
-					echo "sb2-init: ERROR:"
-					echo "sb2-init: *******  CPU transparency ($SB2INIT_CPUTRANSP) seems"
-					echo "sb2-init: *******  to be a statically linked binary, and can't be used."
-					echo "sb2-init: *******  (please specify a dynamically linked alternative"
-					echo "sb2-init: *******  with option -c)"
-					exit 1
-					;;
-				*script*)
-					echo "sb2-init: WARNING:"
-					echo "sb2-init: *******  CPU transparency ($SB2INIT_CPUTRANSP) is a script."
-					echo "sb2-init: *******  This may not work; the program should be a dynamically"
-					echo "sb2-init: *******  linked executable."
-					;;
-				*)
-					echo "sb2-init: WARNING:"
-					echo "sb2-init: *******  Failed to check if the CPU transparency ($SB2INIT_CPUTRANSP)"
-					echo "sb2-init: *******  method is a dynamically linked executable."
-					;;
-			esac
-		else
-			echo "sb2-init: ERROR:"
-			echo "sb2-init: *******  CPU transparency ($SB2INIT_CPUTRANSP) can not"
-			echo "sb2-init: *******  be executed."
-			echo "sb2-init: *******  (please specify a dynamically linked alternative"
-			echo "sb2-init: *******  with option -c)"
-			exit 1
-		fi
-	fi
 fi
 
 # $ARCH has been set, get mode-specific settings..
-if [ -f $SBOX_SESSION_DIR/modes/$MAPPING_MODE/sb2rc ]; then
+if [ -f $SBOX_DIR/share/scratchbox2/modeconf/sb2rc.$MAPPING_MODE ]; then
 	echo "Reading mode-specific settings.."
-	. $SBOX_SESSION_DIR/modes/$MAPPING_MODE/sb2rc "initializing"
+	. $SBOX_DIR/share/scratchbox2/modeconf/sb2rc.$MAPPING_MODE "initializing"
 fi
 
-if [ $SB2INIT_SKIP_CHECKS == "false" ]; then
+if [ ! $SB2INIT_SKIP_CHECKS ]; then
 	check_buildroot_sanity
 fi
 
@@ -478,17 +420,7 @@ if [ -n "$SB2INIT_TOOLS_ROOT" ]; then
 	# else assume standard FHS system
 fi
 
-_host_gcc=$(which gcc)
-if [ -n "$_host_gcc" -a -e "$_host_gcc" ]; then
-	HOST_GCC_INC=$(echo "#include <stdio.h>" | gcc -M -E - | SBOX_DIR=$SBOX_DIR perl -e 'while(<STDIN>) { $foo{$1} = 1 if m/\/usr([^[:space:]]*\/include)/;}; foreach my $k (keys %foo) {print " -isystem $ENV{SBOX_DIR}/share/scratchbox2/host_usr$k"};')
-	SB2INIT_SBOX_HOST_GCC_NAME=host-gcc
-	SB2INIT_SBOX_HOST_GCC_PREFIX_LIST=host-
-else
-	echo "sb2-init: no host-gcc."
-	HOST_GCC_INC=""
-	SB2INIT_SBOX_HOST_GCC_NAME=""
-	SB2INIT_SBOX_HOST_GCC_PREFIX_LIST=""
-fi
+HOST_GCC_INC=$(echo "#include <stdio.h>" | gcc -M -E - | SBOX_DIR=$SBOX_DIR perl -e 'while(<STDIN>) { $foo{$1} = 1 if m/\/usr([^[:space:]]*\/include)/;}; foreach my $k (keys %foo) {print " -isystem $ENV{SBOX_DIR}/share/scratchbox2/host_usr$k"};')
 
 mkdir -p $HOME/.scratchbox2/$TARGET/bin
 write_target_config
@@ -504,7 +436,7 @@ if [ -n "$SB2INIT_REMOTEHOST" ]; then
 fi
 
 # ---------------------------
-# The target can be used now; it is possible to
+# The target can be used now; it is possible to 
 # finalize the configuration by running programs in the new environment.
 
 if [ $SB2INIT_SET_AS_DEFAULT == 1 ]; then
diff --git a/wrappers/dpkg-checkbuilddeps b/wrappers/dpkg-checkbuilddeps
--- a/wrappers/dpkg-checkbuilddeps
+++ b/wrappers/dpkg-checkbuilddeps
@@ -20,7 +20,7 @@
 # Currently there are two algorithms for this: Old and new.
 #
 # The old one, implemented completely as a shell script,
-# ignores many things that should be checked. The new one is
+# ignores many things that should be checked. The new one is 
 # is written in perl, but the implementation is still
 # incomplete. Currently things work so that this shell
 # script digs out the needed variables and feeds them to
@@ -84,8 +84,8 @@ fi
 # are usable thru the current mapping mode:
 TARGET_DPKG_ADMINDIR_USABLE_PKGS=$sbox_temp_dpkg_admin_dir
 
-cfgfile_host_accepted_pkgs=$sbox_dir/share/scratchbox2/modes/$sbox_mapmode/host-accepted-packages
-cfgfile_host_ignored_pkgs=$sbox_dir/share/scratchbox2/modes/$sbox_mapmode/host-ignored-packages
+cfgfile_host_accepted_pkgs=$sbox_dir/share/scratchbox2/modeconf/host-accepted-packages.$sbox_mapmode
+cfgfile_host_ignored_pkgs=$sbox_dir/share/scratchbox2/modeconf/host-ignored-packages.$sbox_mapmode
 
 # Execute a command in tools mode. forces /usr/bin/perl to tools,
 # otherwise the shell which is running this script may try to take perl from
@@ -332,7 +332,7 @@ function check_host_builddeps_by_real_tool()
 	# Run dpkg-checkbuilddeps in the "tools" mode
 	# Note: Can't use a pipeline here, we want to the
 	# dpkg-checkbuilddeps' return status.
-	run_in_tools_mode /usr/share/scratchbox2/wrappers/dpkg-checkbuilddeps-copy-from-wheezy -a i386\
+	run_in_tools_mode /usr/bin/dpkg-checkbuilddeps \
 		$args > $x_missing_dep_file 2>&1
 	if [ $tools_mode_tool_stat == 0 ]; then
 		# real dpkg-checkbuilddeps says "all ok"
@@ -367,14 +367,6 @@ function check_target_builddeps()
 	ret=0
 	verbose_message "SB2 Checking target build deps..."
 	missing_dep_file=`mktemp -p $SBOX_SESSION_DIR/tmp missing_deps.XXXXXXXXXX`
-	BUILD_ARCH=`dpkg-architecture -qDEB_BUILD_ARCH`
-	if [ -z "$SBOX_TARGET" ]; then
-		if [ -r ~/.scratchbox2/config ]; then
-			. ~/.scratchbox2/config
-		fi
-		SBOX_TARGET=$DEFAULT_TARGET
-		. ~/.scratchbox2/$SBOX_TARGET/sb2.config
-	fi
 
 	# dpkg-checkbuilddeps with another package db..
 	# a special rule in the tools mode is needed because the
@@ -382,7 +374,7 @@ function check_target_builddeps()
 	# --admindir option. Can't use a pipeline here, we want to the
 	# dpkg-checkbuilddeps' return status.
 	SBOX_TOOLS_MODE_VAR_LIB_DPKG_STATUS_LOCATION=$TARGET_DPKG_ADMINDIR_USABLE_PKGS/status \
-		run_in_tools_mode /usr/share/scratchbox2/wrappers/dpkg-checkbuilddeps-copy-from-wheezy -a $BUILD_ARCH --admindir="$SBOX_TARGET_ROOT/var/lib/dpkg" \
+		run_in_tools_mode /usr/bin/dpkg-checkbuilddeps \
 			$args > $missing_dep_file 2>&1
 	if [ $tools_mode_tool_stat == 0 ]; then
 		# real dpkg-checkbuilddeps says "all ok"
@@ -413,7 +405,7 @@ function check_target_builddeps()
 	fi
 }
 
-function compare_target_and_host_results_with_new_tool()
+function compare_target_and_host_results_with_new_tool() 
 {
 	t_missing=$missing_deps
 	h_missing=$tools_missing_deps
@@ -435,6 +427,11 @@ function compare_target_and_host_results_with_new_tool()
 		"$t_missing" "$h_missing" "$both_required" "$host_accepted" "$host_ignored"
 	result2=$?
 	return $result2
+	#### if [ $? = 0 ]; then
+	####	result2="ok"
+	####else
+	####	result2="fail"
+	####fi
 }
 
 # First, make sure we are in a correct directory:
@@ -474,6 +471,7 @@ function old_deps_checker()
 
 	# Something is missing. To be able to get the missing packages from the
 	# host environment, at least the list of allowed packages is needed:
+	#
 	if [ ! -f $cfgfile_host_accepted_pkgs ]
 	then
 		verbose_message "OLD_CHK:"
